import 'package:flutter/material.dart';

class Cartoons {
  Image image;
  String name;
  Color color;
  String description;

  Cartoons({
    required this.image,
    required this.name,
    required this.color,
    required this.description,
  });
}

List<Cartoons> cartoondata = [
  Cartoons(
      image: const Image(
        image: AssetImage('assets/images/k.png'),
      ),
      name: 'Kevin',
      color: const Color(
        0xFFff8552,
      ),
      description:
          'Kevin loves to make fun of and tease people or Minions, shown when he made fun of Jerry and teased him for being a coward. He likes playing golf polo and cricket. Kevin has a sense of humor, shown when he thought it was hilarious to see Tom turn into a mutant purple minion, but then immediately showed a cautious side when he realized that he was next to be a victim. In the film Minions, he is the protagonist and leader of the trio in search of a new master. He truly cares about the well-being of the Minion tribe (which is dependent on them having a proper master). '),
  Cartoons(
      image: const Image(image: AssetImage('assets/images/last.png')),
      name: 'Agnes',
      color: const Color(
        0xFFf75b82,
      ),
      description:
          'Agnes, like her sisters, wished to be adopted by someone who cared about her. At first, Agnes is only one out of the three sisters to be excited to be adopted by Gru. She happily hugs his leg and plays games with him, while her sisters are gawking at Gru, their dream of the perfect parents in tatters. She is unaware of Grus own dislike of the whole adoption, her innocence prevailing. She is a very naive, sweet, and innocent child, which is why Margo is so protective of her. She thinks Grus dog is cute and chases after him, despite some protest from Margo'),
  Cartoons(
      image: const Image(image: AssetImage('assets/images/v.png')),
      name: 'Vector',
      color: const Color(0xFF91a7b4),
      description:
          'Vector is highly intelligent, but also overly confident and exceedingly arrogant. Similar to Gru Vectors armory consists of bizarre items beyond imagination of which he often boasts about Vector has a rather excessive fondness for cookies. As such, he eagerly admits Agnes, Edith and Margo into his fortress when they arrived to sell them.  Vector also seems to have an affiliation for aquatic life both marine and freshwater animals as  he keeps an adult great white shark in a large aquarium in his fortress and uses advanced, aquatic-themed weapons such as the squid launcher and the piranha gun. It is even seen that he watches marine life documentaries on his television in his home. Unlike Gru, Vector has no qualms about kidnapping children and taking them as hostages. Even after Gru gives him the moon, he refuses to release Agnes, Edith, and Margo, inciting an angry Gru to enter the fortress and attempt to attack him. '),

   Cartoons(image:const Image(image: AssetImage('assets/images/dr.png')), name: 'Dr. Nefario', color: const Color(0xFF383f49), description: 'Dr. Nefario is Grus closest and most loyal friend who always comes to his rescue. He has a very high respect for Gru and even believes he is the greatest villain in the world, but he often doubts his abilities and motives. He is also quite eccentric with rather bad hearing due to his age, but although he seemed a little odd at times, he did not seem to be going senile. Dr Nefario doesnt like to be unproductive as he has constantly been seen working on projects to aid in Grus crimes and even decides to work for someone else after Gru renounces his former life of villainy. His accent suggests a British family lineage. Nefario seems to enjoy disco dancing and is even briefly shown doing so alongside Marlena Gru, and in the Boogie Robot scene. ')       ,
   Cartoons(image: const Image(image: AssetImage('assets/images/gg.png')), name: 'Margo Gru', color: const Color(0xFF86d7f5), description: 'Margo tends to be a sensitive and straight to the point girl who is very untrusting of people as she takes a long time to warm up to Felonius Gru and she also does not trust his minions to begin with. She is quite optimistic despite her difficulty trusting people, telling the girls that they will be happy with Gru eventually. When Gru goes after them when they are kidnapped by Vector, she is happy to see him but she is still unsure whether to go back as he gave them away again, but she encouraged Edith and Agnes to jump when Gru makes a heartfelt apology. After he rescues them, she finally accepts him. When Gru told the story of how they changed his life and kisses them goodnight, Margo says that she loves him, finally viewing him as her dad. After Gru married Lucy Wilde, Margo had time accepting her as a mother especially when the latter tried too hard or too little in bonding with her and the others. However, after Lucy defended her from Nikos Mother, she did change her perspective and hugged her for defending her honor. She was also happy Lucy came to rescue her and the others from Bratts destruction of Hollywood. '),
   Cartoons(image: const Image(image: AssetImage('assets/images/o.png')), name: 'Edith', color: const Color(0xFFa80214), description: 'Edith is currently the least explored of the three sisters, which is understandable considering she is the middle child, the likes of which are stereotypically neglected by their parents.Edith playing with a weapon She shares many traits with Gru, being very destructive, tomboyish and sports a macabre sense of humor. In the beginning, she is reserved and quiet - being opposed to the idea of being an adopted child. Upon seeing all of Grus weapons and torture devices, her dark, destructive nature is shown when she nonchalantly walks into an iron maiden and starts playing with Grus dangerous weapons in his lab. She breaks glass bottles with foreign substances in them, plays with Grus weapons, and at one point pokes at one of the bottles and asks, "Can I drink this? at which Dr. Nefario responds with,Do you want to explode In response to his answer, she kicks him in the shin and runs off. Edith is also good at ballet, and loves doing it with her sisters. She appears athletic and agile in the second film, and proficient with many weapons and fighting techniques, including the katana and nunchaku. She had also apparently learned Japanese, as she responds in Japanese when Gru warns her not to destroy anything at the Cinco de Mayo party. She seems to be braver than her two sisters, as she prepared to fight a loose evil minion while her two sisters stayed behind her. She also expresses disgust at open affection, saying "Can I be the first to say... Eew!" when Margo and Antonio go out on a date with each other, and when Gru and Lucy kiss at their wedding.  '),
  Cartoons(image: const Image(image: AssetImage('assets/images/l.png')), name: 'Stuart ', color: const Color(0xFF4181b4), description: 'Stuart is playful, friendly, intelligent and funny. He is skillful at video games like his friend Dave. He can also be the most sincere and innocent out of all the minions. He also seems to have a rebellious and obstreperous attitude. He is considered to be a slacker among the other Minions, preferring to chill out and play the ukulele than listen to the rules. Also, he was said to be always hungry in Minions, such as when he attempted to eat Kevin and Bob when he was thinking of them as bananas, and even tried to eat a yellow fire hydrant in New York, also thinking it as a banana or food as well. '),
  Cartoons(image: const Image(image: AssetImage('assets/images/de.png')), name: 'Dave ', color: const Color(0xFFf86f1b), description: 'Dave is an intelligent minion who is kind, caring, and funny, but sometimes accident-prone. He is skillful at video games like his friend Stuart, shown when the two are playing on a gaming console. Dave likes ice cream, as shown when Gru calls him and Stuart while they are having an Ice Cream Party, he is still eating Ice Cream before he goes to Gru. He is always very excited as seen when he fired his Rocket Launcher, his signature weapon. He is also good at using weapons and making cupcakes, among other foods. He also has some good fighting skills, it is shown when he swing around the pole to kick an evil minion and it fell on the ground with the others. '),
  Cartoons(image: const Image(image: AssetImage('assets/images/jr.png')), name: 'Jerry', color: const Color(0xFFffd559), description: 'Jerry is usually described as an excited, carefree and cheeky mouse, he in several episodes is shown to be cold as he seeks to have fun no matter who he harms, which to Tom anger his sense of fun is sadistic, but he also has other targets although Tom is the main one among them, but this last characteristic seems to have a limit as in the episode "The Lonesome Mouse" he regrets having set up Tom to be kicked out of the house. Also Jerry gets Tom in trouble by the humans, who sometimes does not see Jerry because he is small.Although Jerry is usually seen being chased by Tom, he takes the opportunity to attack when he has the advantage of the situation, an example of this is in the episode "Baby Puss" where when he sees Tom drinking milk from a bottle he decides to attract the other cats on the street so that they start making fun of him (important to point out that the end of the episode is bad for Jerry). '),
 Cartoons(image: const Image(image: AssetImage('assets/images/tt.png')), name: 'Tom cat', color: const Color(0xFFcccdcf), description: 'Tom personality has changed remarkably over the years, especially after the first episodes. For example, in his debut, he was quadrupedal and had normal cat intelligence. However, over the years (since the episode Dog Trouble), he has become almost completely bipedal and has superhuman level of intelligence. As a slapstick cartoon character, Tom has a superhuman level of elasticity. Tom is usually defeated (or very rarely, killed) with Jerry getting the best of him in the end, although there are some stories where he outwits, defeats and gets the best of Jerry. '),
 Cartoons(image: const Image(image: AssetImage('assets/images/pe.png')), name: 'Peter Griffin', color: const Color(0xFFfdea80), description: 'Peter favorite pastime is watching TV, with his favorite shows consisting of Star Trek, Three Company and Charles in Charge. He is also a huge KISS fan and followed them during the KISS Stock shows and even got a copy of Kiss Saves Santa for Christmas. Peter is also an ardent fan of Barry Manilow, though this is a fact he has been known to deny in public. Peter also mentioned that he enjoys the following breakfast cereals: Total, Trix, and Boo Berry. Peter also has a habit of proving his masculinity, not wanting Lois to fall for another man. He is incredibly jealous of other attractions Lois has in her life, an attitude that tends to get out of hand in most cases; in "Stuck Together, Torn Apart, he goes so far as to punch his reflection in the mirror after Lois comments on it being handsome. In "Brian Sings and Swings", he threatens to kill both Lois and her other partner in the scenario of her having sex with another man, though when he catches her in bed with Bill Clinton in "Bill and Peter Bogus Journey, he takes no hostile actions whatsoever. However, he seems not to mind the fact that she slept with other men before they met, just so long as she does not do so again; he is particularly proud of the fact that she once slept with Gene Simmons of Kiss when he discovers this in Road to Europe, but forbids any sexual activity between the two now as seen in Don not Make Me Over. '),
Cartoons(image: const Image(image: AssetImage('assets/images/lk.png')), name: 'Brian Griffin', color: const Color(0xFFbf0226), description: 'Brian has a cultured background; he loves opera and jazz, and is a fan of John Coltrane. Brian speaks fluent French and Tagalog, and is competent in Spanish. He is also a member of MENSA. He loves to sing and can imitate a barbershop quartet without accompaniment. He is also an avid writer, having once been invited to write for The New Yorker, although he was fired once the magazine learned he did not graduate from college. He has also written a novel, although has made little progress other than the title Faster Than the Speed of Love, and a synopsis similar to the film "Iron Eagle III", for which Stewie and Lois mock him, and this subject has since been brought up several times throughout the series. He is a smoker, an alcoholic and recovered cocaine addict. Brian discovered that his cocaine habit stemmed from his mother abandoning him for which he saw a therapist. He has also made references to either buying, being in possession of, or smoking marijuana in numerous episodes. In "420", he actually does a whole dance to the song A Bag of Weed. In "It Takes a Village Idiot, and I Married One", it is revealed he has a Ziggy tattoo. It is shown in "Brian & Stewie" that he keeps a gun just in case he wants to commit suicide. '),
Cartoons(image: const Image(image: AssetImage('assets/images/gj.png')), name: 'Lois Griffin', color: const Color(0xFFd0be91), description: 'Though initially appearing to be a typical doting house wife and ideal mother, Lois has many dark aspects to her and in some cases be worse than her husband, except without the excuse of mild retardation. Lois appears to have a taste for Sadomasochism (S&M), dressing as a dominatrix in "Lets Go to the Hop, putting out a lit cigarette on her arm in Breaking Out is Hard to Do, asking Peter to put his finger in a bullet hole and twist it when he accidentally shot her in "Barely Legal" and directing Peter to kick her breasts in "Brian Got a Brand New Bag". Several times Lois has forced Peter to have intercourse with her, yet she sees nothing wrong with this as she believes men can not be forced to have sex.She has made it clear several times that she never wanted to be a mother. In A Fish out of Water when her and Meg go on spring break, during the awkward car ride she tells Meg that she took birth control but taking antibiotics made it not work, evidently causing Meg birth. In Peters Daughter" she instructs Meg on how to have a miscarriage. Chris was also said to be the result of a broken condom in Emission Impossible with the resulting lawsuit paying for the Griffin house. '),
Cartoons(image: const Image(image: AssetImage('assets/images/pi.png')), name: 'Pink Panther', color: const Color(0xFFe97fa9), description: 'The Pink Panther is often seen in episodes as a prankster, as he likes pulling pranks on the janitor whenever he is seen. He has a high level of curiosity, as he loves discovering and trying new things. He is shown to like hospital treatment more than other types and likes the habit of eating and for some reasons, going on a diet to lose weight when overweight. He is often shown to want things done his way, such as tampering with the Mona Lisa and painting a house that is supposed to be blue, going to opposites in both cases. He is also very sneaky, not using force to get what he wants, but rather depending on sneaky tricks to go about his goals. '),
Cartoons(image: const Image(image: AssetImage('assets/images/po.png')), name: 'Pooh', color: const Color(0xFFfdbe57), description: 'Pooh is described as being "a bear of very little brain." He is generally kind and friendly towards everyone and has a demeanor that is childlike and innocent. Because of his limited intelligence, however, Pooh is extremely naive. Absent-minded and simple, he tends to process things at a slower pace than his friends, to the point of seeming disoriented. Pooh sluggish nature also makes him somewhat passive in most situations. Pooh is arguably best known for his love of honey (or "hunny" as he spells it). He keeps a supply of pots at his home, but they are often empty due to his unending appetite. When he runs out, he often travels to Rabbit house to borrow some. Loyal to his friends and the "favored" toy of Christopher Robin, Pooh is often entitled to leader of the group. He has a knack for being very optimistic during times of despair. He can be very courageous in tough times and is usually the one consulted when trouble occurs. '),
Cartoons(image: const Image(image: AssetImage('assets/images/ml.png')), name: 'Mirabel Madrigal', color:const Color(0xFFbb4c9e), description: 'Mirabel often shows a free-spirited and optimistic demeanor; despite being the only Madrigal grandchild without a gift and an outcast by her family and peers, she is still very much sociable and friendly to those around her. Lacking a gift of her own, she admires her relatives and hold them in high regard. Her lack of gift also does not hinder her from getting along with most of her relatives: notably her parents, her cousin Antonio, her elder sister Luisa and her uncle Bruno. She also is humble and honest, admitting easily that she and her father are both accident-prone. On top of this, Mirabel appears confident as she claims that she does not need a gift to make herself happy and that she is just as special as everyone else in her family. '),
Cartoons(image: const Image(image: AssetImage('assets/images/sd.png')), name: 'Sid', color: const Color(0xFFe2d87e), description: 'Sid is a ground sloth who stands and walks like a human with ping-pong ball-like eyes (one is bigger then the other), a button nose, buck teeth and whitish yellow fur. Sid has long claws on his hands and feet and a curled tail. He is talkative and positive, and suffers from a lateral lisp, which makes his "s" and "c" pronunciation rather "wet" or "spitty". Sid is usually the one getting knocked about. He is considered as the only character with bad karma. '),
Cartoons(image: const Image(image: AssetImage('assets/images/ha.png')), name: 'Manfred', color: const Color(0xFF9c5812), description: 'As a mammoth, Manny was short for words, and often came off as ill-tempered, sulky and aloof: this demeanor was brought on by the loss of his family at the hands of a pack of humans. Though he was often ill-disposed, Manny was loyal to those he cared for and watched closely over any that he formed bonds with; though he was dedicated to anyone he was close to, Manny was never above his typical cynicism, or, as Sid was concerned, a sharp slap to the head. But he is still shown to have a good heart. Diego even refers to him as a good guy to which Sid concurs. In later years, Manny demeanor softened as he grew into a herd and found a second wife in the form of Ellie: perhaps due to his losses in life, Manny was greatly protective of Ellie and loved her dearly, this love furthering itself as he became a father for a second time to Peaches, his daughter. With his daughter, Manny grew overly protective and somewhat doting, thinking that Peaches was constantly going to be his helpless baby; this perspective changed as Peaches proved her self-sufficence. '),
Cartoons(image: const Image(image: AssetImage('assets/images/sh.png')), name: 'Diego ', color: const Color(0xFFd3ae7f), description: 'Before meeting the herd, Diego was a wild, vengeful, aggressive, and ruthless saber-toothed cat. He was blindly loyal to his pack and their leader Soto who both shared a mutual respect for one another and was tasked with retrieving the baby from a human tribe as revenge for them killing nearly half of their pack. However, when he failed, Diego would either find the human baby or die.After meeting Manny and Sid who were protecting the child he was supposed to deliver to Soto, Diego tricked them into going to Half Peak where he says the baby parents are waiting but his pack is and will kill the three of them, showing that he was quite uncaring. At first Diego and Manny relationship had an incredibly rocky start, the two did not trust one another nor value either as friends. However, as they continue their journey, Diego discovers Manny tragic backstory and when the mammoth risks his own life to save Diego, the two became extremely close friends. His relationship with Sid, on the other hand, was an instant dislike and constant annoyance. On more than one occasion, he came close to killing him with his teeth. However, the two have a very strong bond and are close friends possibly more than Manny even if the two might not trust each other. '),
Cartoons(image: const Image(image: AssetImage('assets/images/po2.png')), name: 'Po ', color: const Color(0xFF1c130e), description: 'Po is usually easygoing, playful, and cocky like a big kid, as well as rather "fanboyish" when expressing his love for kung fu. In the first film, he is seen as a huge kung fu fan, owning posters and action figures of his favorite warriors, but is himself clumsy, portly, and having low self-confidence, only dreaming he could be a great warrior while feeling stuck in his unfulfilling life at his father noodle shop. But when given the chance, he is all too eager to learn kung fu the hard way, enduring physical beatings and insults in hopes of changing who he is. After learning that there is no secret ingredient, Po shows the inner strength to save the Valley of Peace by using his own skills and ingenuity and in the end becomes his own hero. '),
Cartoons(image: const Image(image: AssetImage('assets/images/tg2.png')), name: 'Tigress ', color: const Color(0xFFd5a52c), description: 'Tigress is the strongest and boldest of the Furious Five. She is noted to have the typical qualities of a hero: overachieving, brave, fearless, and willing to do anything to save the day. The one exception to her willingness, however, was to believe in Po, whom she thought was a joke. But even the strongest can be wrong, and Tigress learned that destiny sometimes arrives in unexpected ways. Since the events of the first film, she has been unwaveringly loyal to Po and what he represents as the Dragon Warrior. But underneath her stoic, iron-jawed exterior is a warm compassion that others seldom see.'),
Cartoons(image: const Image(image: AssetImage('assets/images/si.png')), name: "Shifu ", color: const Color(0xFFae7c44), description: 'Master Shifu was seen as a loving father and devoted teacher to a young Tai Lung when the cub first showed up. But after Tai Lung betrayal, he became distant, a firm and uncompromising taskmaster to his students. It was not until he expected to depart from his students one last time that he confessed he was proud of them all, including Tigress, who especially sought to earn his approval. Since Po heroism in becoming the Dragon Warrior, Shifu has let go of his bitterness and attained inner peace.He also appears to have a bit of a devious side, and before befriending Po, was shown to have a cruel sense of humor. This was shown from the moment Shifu met Po, as he seemed to take delight in trying to drive the amateurish panda away, slowly turning up the heat with every challenge he gave Po and chuckling to himself at his incompetence.'),
Cartoons(image: const Image(image: AssetImage('assets/images/tg.png')), name: 'Tai Lung', color: const Color(0xFF493f59), description: 'As an adult, Tai Lung was shown to be dark, dangerous, and arrogant. However, in the past when he was raised and trained by Shifu, he seemed to be a happy, energetic cub with much talent and dedication to the arts of kung fu and was viewed as a kung fu prodigy in the eyes of his loving father and master. Over the years, Tai Lung grew to into a strong and fierce warrior, having achieved much as a student, even mastering all one thousand scrolls of kung fu.However, his ultimate goal was to be the Dragon Warrior and be handed the Dragon Scroll, which he firmly believed was his destiny. However, at the moment when Shifu presented him to Oogway, the old master indicated Tai Lung was not the one, much to their shock. Expecting Shifu to speak for him on his behalf, he received an emotional blow when his master made no attempt to protest and Tai Lung saw this as an act of betrayal. It was this double rejection that revealed the darkness in Tai Lung heart, expressed in pure rage as he attacked and ravaged the Valley of Peace and later ruthlessly struck Shifu aside when he tried to stop him from taking the Dragon Scroll by force. '),
Cartoons(image: const Image(image: AssetImage('assets/images/ba.png')), name: 'Master Crane', color: const Color(0xFF664e2f), description: 'Crane has demonstrated a dry sense of sarcastic humor on occasion. In his spare time, he enjoys practicing the ancient art of Chinese calligraphy, especially as a way to meditate or wind down after a stressful day.[9] Though brave and reliable, he also tends to show more nervousness than his companions. As demonstrated in the short The Pull-Up Mandate, Crane tends to tease Po physical looks when he stated He cant even lift his arms!".In addition to his Kung Fu skills, Crane is always there to correct Po whenever he gets his facts wrong or needs to memorize a spell. Whether it is about Oogway construction of the Jade Palace, figuring out where to find the Sacred Sun Orchid, or even how to stay calm in a disturbing situation, he always strives to inform and educate others when he has a chance. When a touchy subject arises, he will give certain facial cues or use signals to hide any embarrassing details. In part one of the episode Emperor  Rule, Crane gives Po a bag that features an ingredient used to supplement important vitamins in tea. He notes it will help Po with that "problem" he has. When Po asks, "Which problem?", Crane uses an interesting facial cue: By looking down and up with his eyes, he signals to Po what the problem is. Of course, Po remembers, and thanks him. Not only is this a crucial moment in Crane life, but it gives us the power to know how he thinks and what points he wants to get across.  '),
Cartoons(image: const Image(image: AssetImage('assets/images/mr.png')), name: 'Mr. Bean', color: const Color(0xFFf1c5a2), description: 'Mr. Bean is often portrayed as a childish buffoon. He is usually obnoxious, crazy, selfish and sometimes seems stupid. He can sometimes be a gentlemen towards other women but he does not show much care to his girlfriend which was proven in many episodes (live-action and animated). Mr. Bean often pretends his teddy is real but he doesn not always treat Teddy nicely. Mr. Bean is also a pain to the Reliant Regal in loads of episodes becoming a running gag in the series. In a few occasions, Mr. Bean had been a bit kind but he rarely shows it. He also tends to hate Irma kissing him, and whenever Irma does this to him, he would usually smudge his cheek. ')










];
